language: csharp
solution: AspNetCore.Identity.Elastic.sln
install:
  - nuget restore solution-name.sln
  - nuget install xunit.runners -Version 2.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release AspNetCore.Identity.Elastic.sln
  - mono ./testrunner/xunit.runners.2.2.0/tools/xunit.console.clr4.exe ./tests/AspNetCore.Identity.Elastic.Tests/bin/Release/netcoreapp1.1/AspNetCore.Identity.Elastic.dll
mono: none
dotnet: 1.0.1
