---
version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION_TAG}
    links:
      - elasticsearch
    ports:
      - 5601:5601
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION_TAG}
    ports:
      - 9200:9200
    environment:
      - cluster.name=auth-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK